name: Hiperhidrosis Indonesia
favicon: null
layout_spectrum: 0.50917
typography_spectrum: 0.49633
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d3d3d3'
    - '#ababab'
    - '#5d5d5d'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
