name: Hiperhidrosis Indonesia
favicon: null
layout_spectrum: 0
typography_spectrum: 0.49633
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#86d594'
    - '#ffffff'
    - '#000000'
    - '#5f9267'
    - '#4f4f4f'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
