name: Hiperhidrosis Indonesia
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: 'Kendalikan Keringatmu, Kawan!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050a04'
    - '#2d541f'
    - '#599032'
    - '#aaca9b'
    - '#d7e7dc'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
