name: Hiperhidrosis Indonesia
favicon: null
layout_spectrum: 0
typography_spectrum: 0.9991
title: 'Kendalikan Keringatmu, Kawan!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#852e24'
    - '#1d0000'
    - '#f9f9f7'
    - '#768135'
    - '#395017'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
